name: Minesweeper
on: [push, pull_request]
jobs:
  golangci-lint:
    name: Linting Nutrinow Backend
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Revive Linter
        uses: docker://morphy/revive-action:v2
        with:
          config: revive-linter.toml